LIBNAME JULIA "/sasdata/Credito_Estudos/POL/JULIA_UEHARA";
LIBNAME ART "/sasdata/Credito_Estudos/POL/ARTHUR_FONTANA";
LIBNAME ONED "/sasdata/Credito/ONEDATA/FPD";
LIBNAME LOG_NOVO "/sasdata/Credito/LOGS_PCO/B2C/";
LIBNAME INF "/sasdata/Credito_Estudos/POL/ARTHUR_FONTANA/INFERENCIA";

DATA LOG;
SET 
/*LOG_NOVO.LOGS_PCO_B2C_202509 (where=(IDENTIFICA_NOVA_ARVORE = "NOVO FLUXO B2C" and ORIGEM = "AM" AND FL_DEDUP_CNL_DIA = 1) keep=LOGIN_SOLICITANTE NR_PROPOSTA NR_DOC SAFRA_CNST  DT_CNST RISCO_CEP_CALC_PCO ORIGEM CANAL_PCO_DECISAO OPERACAO TP_PEDIDO BUREAU_PCO RESTRITIVOS_SERASA RGNL_CNST DS_VAR_PRINCIPAL FAIXA_SCORE DS_VAR_ADICIONAL MODELO_ADICIONAL DECISAO_ANALISE REASON_CODE DS_REASON_CODE CD_SCORE POLITICA_NOVA IDENTIFICA_NOVA_ARVORE IDENTIFICA_GRUPO_MODELO GALHO_ARVORE FL_DEDUP_CNL_DIA)*/
/*LOG_NOVO.LOGS_PCO_B2C_202510 (where=(IDENTIFICA_NOVA_ARVORE = "NOVO FLUXO B2C" and ORIGEM = "AM" AND FL_DEDUP_CNL_DIA = 1) keep=LOGIN_SOLICITANTE NR_PROPOSTA NR_DOC SAFRA_CNST  DT_CNST RISCO_CEP_CALC_PCO ORIGEM CANAL_PCO_DECISAO OPERACAO TP_PEDIDO BUREAU_PCO RESTRITIVOS_SERASA RGNL_CNST DS_VAR_PRINCIPAL FAIXA_SCORE DS_VAR_ADICIONAL MODELO_ADICIONAL DECISAO_ANALISE REASON_CODE DS_REASON_CODE CD_SCORE POLITICA_NOVA IDENTIFICA_NOVA_ARVORE IDENTIFICA_GRUPO_MODELO GALHO_ARVORE FL_DEDUP_CNL_DIA)*/
/*LOG_NOVO.LOGS_PCO_B2C_202511 (where=(IDENTIFICA_NOVA_ARVORE = "NOVO FLUXO B2C" and ORIGEM = "AM" AND FL_DEDUP_CNL_DIA = 1) keep=LOGIN_SOLICITANTE NR_PROPOSTA NR_DOC SAFRA_CNST  DT_CNST RISCO_CEP_CALC_PCO ORIGEM CANAL_PCO_DECISAO OPERACAO TP_PEDIDO BUREAU_PCO RESTRITIVOS_SERASA RGNL_CNST DS_VAR_PRINCIPAL FAIXA_SCORE DS_VAR_ADICIONAL MODELO_ADICIONAL DECISAO_ANALISE REASON_CODE DS_REASON_CODE CD_SCORE POLITICA_NOVA IDENTIFICA_NOVA_ARVORE IDENTIFICA_GRUPO_MODELO GALHO_ARVORE FL_DEDUP_CNL_DIA)*/
/*LOG_NOVO.LOGS_PCO_B2C_202512 (where=(IDENTIFICA_NOVA_ARVORE = "NOVO FLUXO B2C" and ORIGEM = "AM" AND FL_DEDUP_CNL_DIA = 1) keep=LOGIN_SOLICITANTE NR_PROPOSTA NR_DOC SAFRA_CNST  DT_CNST RISCO_CEP_CALC_PCO ORIGEM CANAL_PCO_DECISAO OPERACAO TP_PEDIDO BUREAU_PCO RESTRITIVOS_SERASA RGNL_CNST DS_VAR_PRINCIPAL FAIXA_SCORE DS_VAR_ADICIONAL MODELO_ADICIONAL DECISAO_ANALISE REASON_CODE DS_REASON_CODE CD_SCORE POLITICA_NOVA IDENTIFICA_NOVA_ARVORE IDENTIFICA_GRUPO_MODELO GALHO_ARVORE FL_DEDUP_CNL_DIA)*/
/*LOG_NOVO.LOGS_PCO_B2C_202601 (where=(IDENTIFICA_NOVA_ARVORE = "NOVO FLUXO B2C" and ORIGEM = "AM" AND FL_DEDUP_CNL_DIA = 1) keep=LOGIN_SOLICITANTE NR_PROPOSTA NR_DOC SAFRA_CNST  DT_CNST RISCO_CEP_CALC_PCO ORIGEM CANAL_PCO_DECISAO OPERACAO TP_PEDIDO BUREAU_PCO RESTRITIVOS_SERASA RGNL_CNST DS_VAR_PRINCIPAL FAIXA_SCORE DS_VAR_ADICIONAL MODELO_ADICIONAL DECISAO_ANALISE REASON_CODE DS_REASON_CODE CD_SCORE POLITICA_NOVA IDENTIFICA_NOVA_ARVORE IDENTIFICA_GRUPO_MODELO GALHO_ARVORE FL_DEDUP_CNL_DIA)*/
/*LOG_NOVO.LOGS_PCO_B2C_202602 (where=(IDENTIFICA_NOVA_ARVORE = "NOVO FLUXO B2C" and ORIGEM = "AM" AND FL_DEDUP_CNL_DIA = 1) keep=LOGIN_SOLICITANTE NR_PROPOSTA NR_DOC SAFRA_CNST  DT_CNST RISCO_CEP_CALC_PCO ORIGEM CANAL_PCO_DECISAO OPERACAO TP_PEDIDO BUREAU_PCO RESTRITIVOS_SERASA RGNL_CNST DS_VAR_PRINCIPAL FAIXA_SCORE DS_VAR_ADICIONAL MODELO_ADICIONAL DECISAO_ANALISE REASON_CODE DS_REASON_CODE CD_SCORE POLITICA_NOVA IDENTIFICA_NOVA_ARVORE IDENTIFICA_GRUPO_MODELO GALHO_ARVORE FL_DEDUP_CNL_DIA)*/
/*LOG_NOVO.LOGS_PCO_B2C_202603 (where=(IDENTIFICA_NOVA_ARVORE = "NOVO FLUXO B2C" and ORIGEM = "AM" AND FL_DEDUP_CNL_DIA = 1) keep=LOGIN_SOLICITANTE NR_PROPOSTA NR_DOC SAFRA_CNST  DT_CNST RISCO_CEP_CALC_PCO ORIGEM CANAL_PCO_DECISAO OPERACAO TP_PEDIDO BUREAU_PCO RESTRITIVOS_SERASA RGNL_CNST DS_VAR_PRINCIPAL FAIXA_SCORE DS_VAR_ADICIONAL MODELO_ADICIONAL DECISAO_ANALISE REASON_CODE DS_REASON_CODE CD_SCORE POLITICA_NOVA IDENTIFICA_NOVA_ARVORE IDENTIFICA_GRUPO_MODELO GALHO_ARVORE FL_DEDUP_CNL_DIA)*/
/*LOG_NOVO.LOGS_PCO_B2C_202604 (where=(IDENTIFICA_NOVA_ARVORE = "NOVO FLUXO B2C" and ORIGEM = "AM" AND FL_DEDUP_CNL_DIA = 1) keep=LOGIN_SOLICITANTE NR_PROPOSTA NR_DOC SAFRA_CNST  DT_CNST RISCO_CEP_CALC_PCO ORIGEM CANAL_PCO_DECISAO OPERACAO TP_PEDIDO BUREAU_PCO RESTRITIVOS_SERASA RGNL_CNST DS_VAR_PRINCIPAL FAIXA_SCORE DS_VAR_ADICIONAL MODELO_ADICIONAL DECISAO_ANALISE REASON_CODE DS_REASON_CODE CD_SCORE POLITICA_NOVA IDENTIFICA_NOVA_ARVORE IDENTIFICA_GRUPO_MODELO GALHO_ARVORE FL_DEDUP_CNL_DIA)*/
LOG_NOVO.LOGS_PCO_B2C_202605 (where=(IDENTIFICA_NOVA_ARVORE = "NOVO FLUXO B2C" and ORIGEM = "AM" AND FL_DEDUP_CNL_DIA = 1) keep=LOGIN_SOLICITANTE NR_PROPOSTA NR_DOC SAFRA_CNST  DT_CNST RISCO_CEP_CALC_PCO ORIGEM CANAL_PCO_DECISAO OPERACAO TP_PEDIDO BUREAU_PCO RESTRITIVOS_SERASA RGNL_CNST DS_VAR_PRINCIPAL FAIXA_SCORE DS_VAR_ADICIONAL MODELO_ADICIONAL DECISAO_ANALISE REASON_CODE DS_REASON_CODE CD_SCORE POLITICA_NOVA IDENTIFICA_NOVA_ARVORE IDENTIFICA_GRUPO_MODELO GALHO_ARVORE FL_DEDUP_CNL_DIA)
LOG_NOVO.LOGS_PCO_B2C_202606 (where=(IDENTIFICA_NOVA_ARVORE = "NOVO FLUXO B2C" and ORIGEM = "AM" AND FL_DEDUP_CNL_DIA = 1) keep=LOGIN_SOLICITANTE NR_PROPOSTA NR_DOC SAFRA_CNST  DT_CNST RISCO_CEP_CALC_PCO ORIGEM CANAL_PCO_DECISAO OPERACAO TP_PEDIDO BUREAU_PCO RESTRITIVOS_SERASA RGNL_CNST DS_VAR_PRINCIPAL FAIXA_SCORE DS_VAR_ADICIONAL MODELO_ADICIONAL DECISAO_ANALISE REASON_CODE DS_REASON_CODE CD_SCORE POLITICA_NOVA IDENTIFICA_NOVA_ARVORE IDENTIFICA_GRUPO_MODELO GALHO_ARVORE FL_DEDUP_CNL_DIA)
;


RUN;


PROC SQL;
CREATE TABLE INF.LOG_05_06 AS
SELECT 
NR_PROPOSTA,
NR_DOC,
SAFRA_CNST AS SAFRA,
DT_CNST,
RISCO_CEP_CALC_PCO AS RISCO_CIDADE_SERASA,
ORIGEM AS SISTEMA,
CANAL_PCO_DECISAO,
LOGIN_SOLICITANTE,
OPERACAO,
TP_PEDIDO,
BUREAU_PCO,
RESTRITIVOS_SERASA,
RGNL_CNST,
DS_VAR_PRINCIPAL,
FAIXA_SCORE AS FX_SCORE,
DS_VAR_ADICIONAL,
MODELO_ADICIONAL,
DECISAO_ANALISE,
REASON_CODE,
DS_REASON_CODE,
CD_SCORE AS OFERTA,
POLITICA_NOVA,
IDENTIFICA_NOVA_ARVORE,
IDENTIFICA_GRUPO_MODELO,
GALHO_ARVORE,
FL_DEDUP_CNL_DIA
FROM LOG;
RUN;



PROC SQL;
CREATE TABLE art.FPD_GS AS 
SELECT 
A.*,
B.fl_ftra_paga,
B.fl_ftra_parc_over_30,
B.fl_ftra_parc_over_60,
B.fl_atrs_parc_over_30,
B.fl_atrs_parc_over_60,
B.FL_REDUTOR,
B.FL_FATURADO,
B.FL_PLNO_ZERO,
B.FL_LNHA_FICT,
B.FL_DEDUP_CONTA
FROM LOG_TRATADA AS A
LEFT JOIN ONED.FPD_ONEDATA AS B
ON A.NR_PROPOSTA = B.NR_PROPOSTA; 
RUN;


PROC SQL;
CREATE TABLE ART.BASE_MODELAGEM_AM AS 
SELECT 
NR_PROPOSTA,
NR_DOC,
SAFRA,
DT_CNST,
RISCO_CIDADE_SERASA,
SISTEMA,
CANAL_PCO_DECISAO,
OPERACAO,
TP_PEDIDO,
BUREAU_PCO,
RESTRITIVOS_SERASA,
RGNL_CNST,
DS_VAR_PRINCIPAL,
FX_SCORE,
DS_VAR_ADICIONAL,
MODELO_ADICIONAL,
DECISAO_ANALISE,
REASON_CODE,
DS_REASON_CODE,
OFERTA,
POLITICA_NOVA,
IDENTIFICA_NOVA_ARVORE,
IDENTIFICA_GRUPO_MODELO,
GALHO_ARVORE,
fl_ftra_parc_over_30,
fl_ftra_parc_over_60,
fl_atrs_parc_over_30,
fl_atrs_parc_over_60,
FL_REDUTOR,
FL_FATURADO	,
FL_PLNO_ZERO,
FL_LNHA_FICT,
FL_DEDUP_CONTA
FROM FPD_GS
WHERE FL_DEDUP_CNL_DIA = 1; 
RUN;


PROC SORT DATA=ART.BASE_MODELAGEM_AM NODUPKEY; BY NR_PROPOSTA; RUN;

DATA BASE_SRS_GS;
SET ART.BASE_MODELAGEM_AM (where=(SAFRA >= 202510 and IDENTIFICA_NOVA_ARVORE = "NOVO FLUXO B2C") KEEP=NR_DOC NR_PROPOSTA SAFRA	RISCO_CIDADE_SERASA	SISTEMA	CANAL_PCO_DECISAO	OPERACAO	TP_PEDIDO	DS_VAR_PRINCIPAL	FX_SCORE	DS_VAR_ADICIONAL	MODELO_ADICIONAL	DECISAO_ANALISE	REASON_CODE	DS_REASON_CODE	IDENTIFICA_GRUPO_MODELO	GALHO_ARVORE	fl_ftra_parc_over_30	fl_atrs_parc_over_30	FL_REDUTOR	FL_PLNO_ZERO	FL_LNHA_FICT	FL_DEDUP_CONTA FL_FATURADO IDENTIFICA_NOVA_ARVORE);

FL_PROPOSTA = 1;

IF DECISAO_ANALISE = "APROVADO" THEN FL_APROVADOS = 1; ELSE FL_APROVADOS = 0;

FL_ALTAS = (FL_FATURADO = 1 and
               FL_REDUTOR = 0 and
               FL_PLNO_ZERO = 0 and
               FL_LNHA_FICT = 0 and
               FL_DEDUP_CONTA = 1);

IF DS_VAR_PRINCIPAL = "" OR FX_SCORE = "" OR DS_VAR_ADICIONAL = "" OR MODELO_ADICIONAL = "" THEN DELETE;

RUN;


/*===========================================================
  OBJETIVO:
    - Criar SCORE_<DS_VAR_PRINCIPAL>  = FX_SCORE
    - Criar ADICIONAL_<DS_VAR_ADICIONAL> = MODELO_ADICIONAL
      * Se DS_VAR_ADICIONAL vazio -> usar DS_VAR_PRINCIPAL
 
  ENTRADA : BASE_SRS_GS
  SAÍDA   : BASE_SRS_GS_tratada
===========================================================*/
 
options validvarname=v7;
 
/*-----------------------------------------------------------
  1) Descobre automaticamente as colunas chave (BY):
     "todas as colunas" menos as 4 que participam do pivot
-----------------------------------------------------------*/
proc sql noprint;
  select name
    into :bycols separated by ' '
  from dictionary.columns
  where libname = 'WORK'
    and memname = 'BASE_SRS_GS'
    and upcase(name) not in
      ('DS_VAR_PRINCIPAL','FX_SCORE','DS_VAR_ADICIONAL','MODELO_ADICIONAL');
quit;
 
%put NOTE: BYCOLS = &bycols.;
 
/* Se quiser definir BY manualmente, comente o PROC SQL acima e use:
   %let bycols = NR_DOC SAFRA;
*/
 
/*-----------------------------------------------------------
  Função inline (via lógica repetida) para "sanitizar" nomes:
   - UPPER
   - troca caracteres inválidos por "_"
   - garante 1º char válido (letra ou "_")
   - trunca para caber em 32 chars (limite SAS V7)
-----------------------------------------------------------*/
 
/*-----------------------------------------------------------
  2) Prepara dataset para SCORE_<DS_VAR_PRINCIPAL>
-----------------------------------------------------------*/
data _principal_prep;
  set BASE_SRS_GS;
 
  length _id $32 _raw $200;
 
  _raw = upcase(strip(DS_VAR_PRINCIPAL));
  _raw = prxchange('s/[^A-Z0-9_]/_/o', -1, _raw);
 
  /* garante início válido */
  if not (('A' <= substr(_raw,1,1) <= 'Z') or substr(_raw,1,1) = '_') then
    _raw = cats('_', _raw);
 
  /* trunca para caber: 32 - length('SCORE_') = 26 */
  _raw = substr(_raw, 1, 32 - length('SCORE_'));
  _id  = cats('SCORE_', _raw);
 
  _value = FX_SCORE;
 
  keep &bycols _id _value;
run;
 
/*-----------------------------------------------------------
  3) Prepara dataset para ADICIONAL_<DS_VAR_ADICIONAL ou DS_VAR_PRINCIPAL>
-----------------------------------------------------------*/
data _adicional_prep;
  set BASE_SRS_GS;
 
  length _id $32 _raw $200 _ds $200;
 
  _ds  = coalescec(strip(DS_VAR_ADICIONAL), strip(DS_VAR_PRINCIPAL));
  _raw = upcase(strip(_ds));
  _raw = prxchange('s/[^A-Z0-9_]/_/o', -1, _raw);
 
  /* garante início válido */
  if not (('A' <= substr(_raw,1,1) <= 'Z') or substr(_raw,1,1) = '_') then
    _raw = cats('_', _raw);
 
  /* trunca para caber: 32 - length('ADICIONAL_') = 22 */
  _raw = substr(_raw, 1, 32 - length('ADICIONAL_'));
  _id  = cats('ADICIONAL_', _raw);
 
  _value = MODELO_ADICIONAL;
 
  keep &bycols _id _value;
run;
 
/*-----------------------------------------------------------
  4) (Opcional, mas recomendado) Tratar duplicidades:
     Se existir mais de uma linha com mesmo BY + _id,
     mantém a última ocorrência (ordem do dataset).
     -> Ajuste aqui se quiser MAX/MIN etc.
-----------------------------------------------------------*/
proc sort data=_principal_prep; by &bycols _id; run;
proc sort data=_adicional_prep; by &bycols _id; run;
 
data _principal_prep2;
  set _principal_prep;
  by &bycols _id;
  if last._id;
run;
 
data _adicional_prep2;
  set _adicional_prep;
  by &bycols _id;
  if last._id;
run;
 
/*-----------------------------------------------------------
  5) Transpose (wide) para criar colunas dinâmicas
-----------------------------------------------------------*/
proc transpose data=_principal_prep2 out=_principal_wide(drop=_name_);
  by &bycols;
  id _id;
  var _value;
run;
 
proc transpose data=_adicional_prep2 out=_adicional_wide(drop=_name_);
  by &bycols;
  id _id;
  var _value;
run;
 
/*-----------------------------------------------------------
  6) Junta os dois blocos (SCORE_* e ADICIONAL_*)
-----------------------------------------------------------*/
proc sort data=_principal_wide; by &bycols; run;
proc sort data=_adicional_wide; by &bycols; run;
 
data BASE_SRS_GS_tratada;
  merge _principal_wide _adicional_wide;
  by &bycols;
run;
 
/*-----------------------------------------------------------
  7) Limpeza (opcional)
-----------------------------------------------------------*/
proc datasets library=work nolist;
  delete _principal_prep _principal_prep2 _principal_wide
         _adicional_prep _adicional_prep2 _adicional_wide;
quit;

DATA ART.BASE_SRS_GS_TRATADA;
SET BASE_SRS_GS_TRATADA;
RUN;

PROC SQL;
CREATE TABLE INF.BASE_MODELAGEM_AM AS
SELECT 
 NR_PROPOSTA
,NR_DOC
,SAFRA
,RISCO_CIDADE_SERASA	
,SISTEMA	
,CANAL_PCO_DECISAO	
,OPERACAO	
,TP_PEDIDO	
,DECISAO_ANALISE	
,REASON_CODE	
,DS_REASON_CODE	
,IDENTIFICA_NOVA_ARVORE	
,IDENTIFICA_GRUPO_MODELO	
,GALHO_ARVORE	
,SCORE_HVI3______________________	AS SCORE_HVI3
,SCORE_BVS_______________________	AS SCORE_BVS
,ADICIONAL_G1_BHV________________	AS ADICIONAL_G1_BHV
,ADICIONAL_REST__________________	AS ADICIONAL_REST
,ADICIONAL_G4_BHV________________	AS ADICIONAL_G4_BHV
,ADICIONAL_G5_BHV________________	AS ADICIONAL_G5_BHV
,ADICIONAL_HVI4__________________	AS ADICIONAL_HVI4
,ADICIONAL_G7_BHV________________	AS ADICIONAL_G7_BHV
,FL_REDUTOR	
,FL_LNHA_FICT
,FL_PLNO_ZERO	
,FL_DEDUP_CONTA	

,SUM(FL_PROPOSTA)		  AS FL_PROPOSTA
,SUM(FL_APROVADOS)		  AS FL_APROVADOS
,SUM(FL_ALTAS)			  AS FL_ALTAS

,SUM(FL_FTRA_PARC_OVER_30) AS FL_FTRA_PARC_OVER_30
,SUM(FL_ATRS_PARC_OVER_30) AS FL_ATRS_PARC_OVER_30

FROM ART.BASE_SRS_GS_TRATADA /*JULIA.BASE_SRS_GS_TRATADA*/
GROUP BY 1,	2,	3,	4,	5,	6,	7,	8,	9,	10,	11,	12,	13,	14,	15,	16,	17,	18,	19,	20,	21,	22,	23,	24,25;
QUIT;

PROC CONTENTS DATA=ART.BASE_SRS_GS_TRATADA; RUN;